### ISSUE TITLE
Map visualization

### ISSUE THREAD

**Issue by larsen** [larsen/rando-planner#2]
It would be nice to display the GPX data on an actual map, and highlight the different segments in the plan

### Todo

- [x] Display maps
  - [x] Passing a GPX file content as a string
  - [x] Passing a GPX file as a URL
- [x] Display multiple maps on the same notebook
- [x] Automatically center the map usign the GPX data
- [x] Resolve unstability issues: [sometimes the notebook displays a "Invalid module" error, that spontaneusly goes away when reloading the page](https://github.com/larsen/rando-planner/issues/21)

**Comment by larsen** [comment]
Current status

![rando-planner-leaflet](https://github.com/larsen/rando-planner/assets/4965/9bf56cca-dbd5-453a-bd91-9f5409bb0979)

**Comment by larsen** [comment]
Current status

![image](https://github.com/larsen/rando-planner/assets/4965/f7bbad67-6851-455b-a9de-1cfbc18ea2e8)
